//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_0._0._0._1.Database_connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hlavni_budova
    {
        public int Id { get; set; }
        public string Cena { get; set; }
        public string Info { get; set; }
        public string Nazev { get; set; }
    }
}
